<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.K9GqhYH' shared service.

return $this->privates['.service_locator.K9GqhYH'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'envoie' => ['privates', '.errored..service_locator.K9GqhYH.App\\Entity\\Transaction', NULL, 'Cannot autowire service ".service_locator.K9GqhYH": it references class "App\\Entity\\Transaction" but no such service exists.'],
    'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
    'serializer' => ['services', 'serializer', 'getSerializerService', false],
    'trepo' => ['privates', 'App\\Repository\\TarifsRepository', 'getTarifsRepositoryService.php', true],
    'validator' => ['services', 'validator', 'getValidatorService', false],
], [
    'envoie' => 'App\\Entity\\Transaction',
    'manager' => '?',
    'serializer' => '?',
    'trepo' => 'App\\Repository\\TarifsRepository',
    'validator' => '?',
]);
