<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.fVPVD8b' shared service.

return $this->privates['.service_locator.fVPVD8b'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'cpt' => ['privates', 'App\\Repository\\CompteRepository', 'getCompteRepositoryService.php', true],
    'dpt' => ['privates', '.errored..service_locator.fVPVD8b.App\\Entity\\Depot', NULL, 'Cannot autowire service ".service_locator.fVPVD8b": it references class "App\\Entity\\Depot" but no such service exists.'],
    'validator' => ['services', 'validator', 'getValidatorService', false],
], [
    'cpt' => 'App\\Repository\\CompteRepository',
    'dpt' => 'App\\Entity\\Depot',
    'validator' => '?',
]);
