# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest: 
    routing_loader:
        default_format: json
        include_format: false
    body_listener: true
    format_listener:
        enabled: true
        rules:
            - { path: ^/api, prefer_extension: true, fallback_format: json, priorities: [ json ] }
    param_fetcher_listener: 'force'
    access_denied_listener:
        json: true
    view:
        formats: { json: true, xml: false, rss: false, html: true }
        view_response_listener:  true
    body_converter:
        enabled: true
        validate: true
        validation_errors_argument: violations
    serializer:
        serialize_null: true
        