<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.sIABFlx' shared service.

return $this->privates['.service_locator.sIABFlx'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\AdminController::addCompte' => ['privates', '.service_locator.Yva8Kfp', 'get_ServiceLocator_Yva8KfpService.php', true],
    'App\\Controller\\AdminController::addUser' => ['privates', '.service_locator.5_k5Atb', 'get_ServiceLocator_5K5AtbService.php', true],
    'App\\Controller\\AdminController::createPart' => ['privates', '.service_locator.mqyMxL7', 'get_ServiceLocator_MqyMxL7Service.php', true],
    'App\\Controller\\AdminController::depot' => ['privates', '.service_locator.1op92k1', 'get_ServiceLocator_1op92k1Service.php', true],
    'App\\Controller\\AdminController::editpart' => ['privates', '.service_locator.Oy.nOIY', 'get_ServiceLocator_Oy_NOIYService.php', true],
    'App\\Controller\\AdminController::setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
    'App\\Controller\\CompteController::delete' => ['privates', '.service_locator.M30T2zO', 'get_ServiceLocator_M30T2zOService.php', true],
    'App\\Controller\\CompteController::edit' => ['privates', '.service_locator.M30T2zO', 'get_ServiceLocator_M30T2zOService.php', true],
    'App\\Controller\\CompteController::index' => ['privates', '.service_locator.JfrEn5y', 'get_ServiceLocator_JfrEn5yService.php', true],
    'App\\Controller\\CompteController::show' => ['privates', '.service_locator.M30T2zO', 'get_ServiceLocator_M30T2zOService.php', true],
    'App\\Controller\\SecurityController::register' => ['privates', '.service_locator.H3qnu8f', 'get_ServiceLocator_H3qnu8fService.php', true],
    'App\\Controller\\AdminController:addCompte' => ['privates', '.service_locator.Yva8Kfp', 'get_ServiceLocator_Yva8KfpService.php', true],
    'App\\Controller\\AdminController:addUser' => ['privates', '.service_locator.5_k5Atb', 'get_ServiceLocator_5K5AtbService.php', true],
    'App\\Controller\\AdminController:createPart' => ['privates', '.service_locator.mqyMxL7', 'get_ServiceLocator_MqyMxL7Service.php', true],
    'App\\Controller\\AdminController:depot' => ['privates', '.service_locator.1op92k1', 'get_ServiceLocator_1op92k1Service.php', true],
    'App\\Controller\\AdminController:editpart' => ['privates', '.service_locator.Oy.nOIY', 'get_ServiceLocator_Oy_NOIYService.php', true],
    'App\\Controller\\AdminController:setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
    'App\\Controller\\CompteController:delete' => ['privates', '.service_locator.M30T2zO', 'get_ServiceLocator_M30T2zOService.php', true],
    'App\\Controller\\CompteController:edit' => ['privates', '.service_locator.M30T2zO', 'get_ServiceLocator_M30T2zOService.php', true],
    'App\\Controller\\CompteController:index' => ['privates', '.service_locator.JfrEn5y', 'get_ServiceLocator_JfrEn5yService.php', true],
    'App\\Controller\\CompteController:show' => ['privates', '.service_locator.M30T2zO', 'get_ServiceLocator_M30T2zOService.php', true],
    'App\\Controller\\SecurityController:register' => ['privates', '.service_locator.H3qnu8f', 'get_ServiceLocator_H3qnu8fService.php', true],
], [
    'App\\Controller\\AdminController::addCompte' => '?',
    'App\\Controller\\AdminController::addUser' => '?',
    'App\\Controller\\AdminController::createPart' => '?',
    'App\\Controller\\AdminController::depot' => '?',
    'App\\Controller\\AdminController::editpart' => '?',
    'App\\Controller\\AdminController::setViewHandler' => '?',
    'App\\Controller\\CompteController::delete' => '?',
    'App\\Controller\\CompteController::edit' => '?',
    'App\\Controller\\CompteController::index' => '?',
    'App\\Controller\\CompteController::show' => '?',
    'App\\Controller\\SecurityController::register' => '?',
    'App\\Controller\\AdminController:addCompte' => '?',
    'App\\Controller\\AdminController:addUser' => '?',
    'App\\Controller\\AdminController:createPart' => '?',
    'App\\Controller\\AdminController:depot' => '?',
    'App\\Controller\\AdminController:editpart' => '?',
    'App\\Controller\\AdminController:setViewHandler' => '?',
    'App\\Controller\\CompteController:delete' => '?',
    'App\\Controller\\CompteController:edit' => '?',
    'App\\Controller\\CompteController:index' => '?',
    'App\\Controller\\CompteController:show' => '?',
    'App\\Controller\\SecurityController:register' => '?',
]);
