<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.uVQN3xu' shared service.

return $this->privates['.service_locator.uVQN3xu'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'encoder' => ['services', 'security.password_encoder', 'getSecurity_PasswordEncoderService.php', true],
    'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
    'user' => ['privates', '.errored..service_locator.uVQN3xu.App\\Entity\\Utilisateur', NULL, 'Cannot autowire service ".service_locator.uVQN3xu": it references class "App\\Entity\\Utilisateur" but no such service exists.'],
    'userRepo' => ['privates', 'App\\Repository\\UtilisateurRepository', 'getUtilisateurRepositoryService.php', true],
], [
    'encoder' => '?',
    'manager' => '?',
    'user' => 'App\\Entity\\Utilisateur',
    'userRepo' => 'App\\Repository\\UtilisateurRepository',
]);
