<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.M1tj3io' shared service.

return $this->privates['.service_locator.M1tj3io'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'part' => ['privates', '.errored..service_locator.M1tj3io.App\\Entity\\Partenaire', NULL, 'Cannot autowire service ".service_locator.M1tj3io": it references class "App\\Entity\\Partenaire" but no such service exists.'],
    'validator' => ['services', 'validator', 'getValidatorService', false],
], [
    'part' => 'App\\Entity\\Partenaire',
    'validator' => '?',
]);
