<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.Ohg05Yt' shared service.

return $this->privates['.service_locator.Ohg05Yt'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'trans' => ['privates', 'App\\Repository\\TransactionRepository', 'getTransactionRepositoryService.php', true],
], [
    'trans' => 'App\\Repository\\TransactionRepository',
]);
