<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.a1rL4gT' shared service.

return $this->privates['.service_locator.a1rL4gT'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'benef' => ['privates', '.errored..service_locator.a1rL4gT.App\\Entity\\Beneficiaire', NULL, 'Cannot autowire service ".service_locator.a1rL4gT": it references class "App\\Entity\\Beneficiaire" but no such service exists.'],
    'envoie' => ['privates', '.errored..service_locator.a1rL4gT.App\\Entity\\Transaction', NULL, 'Cannot autowire service ".service_locator.a1rL4gT": it references class "App\\Entity\\Transaction" but no such service exists.'],
    'exp' => ['privates', '.errored..service_locator.a1rL4gT.App\\Entity\\Expediteur', NULL, 'Cannot autowire service ".service_locator.a1rL4gT": it references class "App\\Entity\\Expediteur" but no such service exists.'],
    'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
    'trepo' => ['privates', 'App\\Repository\\TarifsRepository', 'getTarifsRepositoryService.php', true],
], [
    'benef' => 'App\\Entity\\Beneficiaire',
    'envoie' => 'App\\Entity\\Transaction',
    'exp' => 'App\\Entity\\Expediteur',
    'manager' => '?',
    'trepo' => 'App\\Repository\\TarifsRepository',
]);
