<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.ROIRRrv' shared service.

return $this->privates['.service_locator.ROIRRrv'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'user' => ['privates', 'App\\Repository\\UtilisateurRepository', 'getUtilisateurRepositoryService.php', true],
], [
    'user' => 'App\\Repository\\UtilisateurRepository',
]);
