<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.SZWCsH0' shared service.

return $this->privates['.service_locator.SZWCsH0'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'cpt' => ['privates', '.errored..service_locator.SZWCsH0.App\\Entity\\Compte', NULL, 'Cannot autowire service ".service_locator.SZWCsH0": it references class "App\\Entity\\Compte" but no such service exists.'],
    'dpt' => ['privates', '.errored..service_locator.SZWCsH0.App\\Entity\\Depot', NULL, 'Cannot autowire service ".service_locator.SZWCsH0": it references class "App\\Entity\\Depot" but no such service exists.'],
    'validator' => ['services', 'validator', 'getValidatorService', false],
], [
    'cpt' => 'App\\Entity\\Compte',
    'dpt' => 'App\\Entity\\Depot',
    'validator' => '?',
]);
