<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.4dz2mAD' shared service.

return $this->privates['.service_locator.4dz2mAD'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'cmpt' => ['privates', '.errored..service_locator.4dz2mAD.App\\Entity\\Compte', NULL, 'Cannot autowire service ".service_locator.4dz2mAD": it references class "App\\Entity\\Compte" but no such service exists.'],
    'part' => ['privates', '.errored..service_locator.4dz2mAD.App\\Entity\\Partenaire', NULL, 'Cannot autowire service ".service_locator.4dz2mAD": it references class "App\\Entity\\Partenaire" but no such service exists.'],
], [
    'cmpt' => 'App\\Entity\\Compte',
    'part' => 'App\\Entity\\Partenaire',
]);
