<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.BAAj6Wt' shared service.

return $this->privates['.service_locator.BAAj6Wt'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'cd' => ['privates', '.errored..service_locator.BAAj6Wt.App\\Entity\\Transaction', NULL, 'Cannot autowire service ".service_locator.BAAj6Wt": it references class "App\\Entity\\Transaction" but no such service exists.'],
    'exp' => ['privates', 'App\\Repository\\TransactionRepository', 'getTransactionRepositoryService.php', true],
    'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
    'ret' => ['privates', '.errored..service_locator.BAAj6Wt.App\\Entity\\Transaction', NULL, 'Cannot autowire service ".service_locator.BAAj6Wt": it references class "App\\Entity\\Transaction" but no such service exists.'],
    'validator' => ['services', 'validator', 'getValidatorService', false],
], [
    'cd' => 'App\\Entity\\Transaction',
    'exp' => 'App\\Repository\\TransactionRepository',
    'manager' => '?',
    'ret' => 'App\\Entity\\Transaction',
    'validator' => '?',
]);
