<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.fcCzNGP' shared service.

return $this->privates['.service_locator.fcCzNGP'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'part' => ['privates', '.errored..service_locator.fcCzNGP.App\\Entity\\Partenaire', NULL, 'Cannot autowire service ".service_locator.fcCzNGP": it references class "App\\Entity\\Partenaire" but no such service exists.'],
    'passwordEncoder' => ['services', 'security.password_encoder', 'getSecurity_PasswordEncoderService.php', true],
    'user' => ['privates', '.errored..service_locator.fcCzNGP.App\\Entity\\Utilisateur', NULL, 'Cannot autowire service ".service_locator.fcCzNGP": it references class "App\\Entity\\Utilisateur" but no such service exists.'],
    'violations' => ['privates', '.errored..service_locator.fcCzNGP.Symfony\\Component\\Validator\\ConstraintViolationList', NULL, 'Cannot autowire service ".service_locator.fcCzNGP": it references class "Symfony\\Component\\Validator\\ConstraintViolationList" but no such service exists.'],
], [
    'part' => 'App\\Entity\\Partenaire',
    'passwordEncoder' => '?',
    'user' => 'App\\Entity\\Utilisateur',
    'violations' => 'Symfony\\Component\\Validator\\ConstraintViolationList',
]);
