<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUwzbEbJ\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUwzbEbJ/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUwzbEbJ.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUwzbEbJ\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerUwzbEbJ\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'UwzbEbJ',
    'container.build_id' => '5cc95c87',
    'container.build_time' => 1565883077,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUwzbEbJ');
