<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDCpUAyb\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDCpUAyb/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDCpUAyb.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDCpUAyb\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerDCpUAyb\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'DCpUAyb',
    'container.build_id' => 'ceebe180',
    'container.build_time' => 1565191655,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDCpUAyb');
