<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOS30Dfm\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOS30Dfm/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOS30Dfm.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOS30Dfm\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerOS30Dfm\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'OS30Dfm',
    'container.build_id' => '2c91a8f5',
    'container.build_time' => 1567465439,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOS30Dfm');
