<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.r.oJVmh' shared service.

return $this->privates['.service_locator.r.oJVmh'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'passwordEncoder' => ['services', 'security.password_encoder', 'getSecurity_PasswordEncoderService.php', true],
    'user' => ['privates', '.errored..service_locator.r.oJVmh.App\\Entity\\Utilisateur', NULL, 'Cannot autowire service ".service_locator.r.oJVmh": it references class "App\\Entity\\Utilisateur" but no such service exists.'],
    'validator' => ['services', 'validator', 'getValidatorService', false],
    'violations' => ['privates', '.errored..service_locator.r.oJVmh.Symfony\\Component\\Validator\\ConstraintViolationList', NULL, 'Cannot autowire service ".service_locator.r.oJVmh": it references class "Symfony\\Component\\Validator\\ConstraintViolationList" but no such service exists.'],
], [
    'passwordEncoder' => '?',
    'user' => 'App\\Entity\\Utilisateur',
    'validator' => '?',
    'violations' => 'Symfony\\Component\\Validator\\ConstraintViolationList',
]);
